name: Android CI - Unit Converter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Permission for Gradle
      - name: Grant execute permission
        run: chmod +x gradlew

      # Run unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Add Android Lint
      - name: Run Lint
        run: ./gradlew lint

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

        # Build Release APK (unsigned)
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: unit-converter-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

                # Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: unit-converter-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

